// Copyright 2023 m01i0ng <alley.ma@qq.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/m01i0ng/mblog.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: mblog/v1/mblog.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MBlogClient is the client API for MBlog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MBlogClient interface {
	ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
}

type mBlogClient struct {
	cc grpc.ClientConnInterface
}

func NewMBlogClient(cc grpc.ClientConnInterface) MBlogClient {
	return &mBlogClient{cc}
}

func (c *mBlogClient) ListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, "/v1.MBlog/ListUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MBlogServer is the server API for MBlog service.
// All implementations must embed UnimplementedMBlogServer
// for forward compatibility
type MBlogServer interface {
	ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error)
	mustEmbedUnimplementedMBlogServer()
}

// UnimplementedMBlogServer must be embedded to have forward compatible implementations.
type UnimplementedMBlogServer struct {
}

func (UnimplementedMBlogServer) ListUser(context.Context, *ListUserRequest) (*ListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}
func (UnimplementedMBlogServer) mustEmbedUnimplementedMBlogServer() {}

// UnsafeMBlogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MBlogServer will
// result in compilation errors.
type UnsafeMBlogServer interface {
	mustEmbedUnimplementedMBlogServer()
}

func RegisterMBlogServer(s grpc.ServiceRegistrar, srv MBlogServer) {
	s.RegisterService(&MBlog_ServiceDesc, srv)
}

func _MBlog_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBlogServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MBlog/ListUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBlogServer).ListUser(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MBlog_ServiceDesc is the grpc.ServiceDesc for MBlog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MBlog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.MBlog",
	HandlerType: (*MBlogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUser",
			Handler:    _MBlog_ListUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mblog/v1/mblog.proto",
}
